import type { Command } from "./types";

export const COMMANDS: Command[] = [
  {
    id: "workbench.action.showCommands",
    title: "Show All Commands",
    category: "View",
    keybinding: "Ctrl+Shift+P",
    run: (ctx) => ctx.openPalette(),
  },
  {
    id: "workbench.action.reopenClosedEditor",
    title: "Reopen Closed Editor",
    category: "View",
    keybinding: "Ctrl+Shift+T",
    run: (ctx) => void ctx.reopenClosed(),
  },
  {
    id: "git.clone",
    title: "Clone Repository…",
    category: "Git",
    run: (ctx) => void ctx.cloneRepository(),
  },
  {
    id: "workbench.action.files.openFolder",
    title: "Open Folder…",
    category: "File",
    keybinding: "Ctrl+K Ctrl+O",
    run: (ctx) => void ctx.openFolder(),
  },
  {
    id: "workbench.action.closeFolder",
    title: "Close Folder",
    category: "File",
    run: (ctx) => ctx.closeFolder(),
  },
  {
    id: "workbench.files.action.refreshFilesExplorer",
    title: "Refresh Explorer",
    category: "File",
    run: (ctx) => void ctx.refreshExplorer(),
  },
  {
    id: "workbench.files.action.collapseExplorerFolders",
    title: "Collapse Folders in Explorer",
    category: "File",
    run: (ctx) => ctx.collapseExplorer(),
  },
  {
    id: "workbench.files.action.expandExplorerFolders",
    title: "Expand Folders in Explorer",
    category: "File",
    run: (ctx) => ctx.expandExplorer(),
  },
  {
    id: "workbench.action.quickOpen",
    title: "Go to File…",
    category: "Go",
    keybinding: "Ctrl+P",
    run: (ctx) => ctx.openGoToFile(),
  },
  {
    id: "workbench.action.openGlobalKeybindings",
    title: "Keyboard Shortcuts",
    category: "Preferences",
    keybinding: "Ctrl+K Ctrl+S",
    run: (ctx) => ctx.openKeybindings(),
  },
  {
    id: "workbench.action.addRootFolder",
    title: "Add Folder to Workspace…",
    category: "File",
    run: (ctx) => void ctx.addFolderRoot(),
  },
  {
    id: "workbench.action.removeRootFolder",
    title: "Remove Folder from Workspace…",
    category: "File",
    run: (ctx) => {
      const path = window.prompt("Folder path to remove from the workspace:");
      if (!path?.trim()) return;
      void ctx.removeFolderRoot(path.trim());
    },
  },
  {
    id: "workbench.action.files.save",
    title: "Save",
    category: "File",
    keybinding: "Ctrl+S",
    run: (ctx) => void ctx.save(),
  },
  {
    id: "workbench.action.files.saveAs",
    title: "Save As…",
    category: "File",
    keybinding: "Ctrl+Shift+S",
    run: (ctx) => void ctx.saveAs(),
  },
  {
    id: "workbench.action.files.saveAll",
    title: "Save All",
    category: "File",
    keybinding: "Ctrl+K S",
    run: (ctx) => void ctx.saveAll(),
  },
  {
    id: "workbench.action.closeActiveEditor",
    title: "Close Editor",
    category: "View",
    keybinding: "Ctrl+W",
    run: (ctx) => ctx.closeActive(),
  },
  {
    id: "workbench.action.closeAllEditors",
    title: "Close All Editors",
    category: "View",
    keybinding: "Ctrl+K W",
    run: (ctx) => ctx.closeAll(),
  },
  {
    id: "workbench.action.toggleTheme",
    title: "Toggle Light/Dark Theme",
    category: "Preferences",
    keybinding: "Ctrl+K Ctrl+T",
    run: (ctx) => ctx.toggleTheme(),
  },
  {
    id: "editor.action.formatDocument",
    title: "Format Document",
    category: "Edit",
    keybinding: "Shift+Alt+F",
    run: (ctx) => ctx.runEditorCommand("format"),
  },
  {
    id: "editor.action.showHover",
    title: "Show Hover",
    category: "Edit",
    keybinding: "Ctrl+K Ctrl+I",
    run: (ctx) => ctx.runEditorCommand("hover"),
  },
  {
    id: "editor.action.addSelectionToNextFindMatch",
    title: "Add Selection To Next Find Match",
    category: "Edit",
    keybinding: "Ctrl+D",
    run: (ctx) => ctx.runEditorCommand("addNextMatch"),
  },
  {
    id: "editor.foldAll",
    title: "Fold All",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("foldAll"),
  },
  {
    id: "editor.unfoldAll",
    title: "Unfold All",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("unfoldAll"),
  },
  {
    id: "editor.action.transformToUppercase",
    title: "Transform to Uppercase",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("uppercase"),
  },
  {
    id: "editor.action.transformToLowercase",
    title: "Transform to Lowercase",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("lowercase"),
  },
  {
    id: "editor.action.blockComment",
    title: "Toggle Block Comment",
    category: "Edit",
    keybinding: "Shift+Alt+A",
    run: (ctx) => ctx.runEditorCommand("blockComment"),
  },
  {
    id: "editor.action.joinLines",
    title: "Join Lines",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("joinLines"),
  },
  {
    id: "editor.action.sortLinesAscending",
    title: "Sort Lines Ascending",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("sortLines"),
  },
  {
    id: "editor.action.duplicateSelection",
    title: "Duplicate Selection",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("duplicateSelection"),
  },
  {
    id: "editor.action.transposeLetters",
    title: "Transpose Letters",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("transposeLetters"),
  },
  {
    id: "editor.action.jumpToBracket",
    title: "Go to Matching Bracket",
    category: "Go",
    run: (ctx) => ctx.runEditorCommand("jumpToBracket"),
  },
  {
    id: "editor.action.selectHighlights",
    title: "Select All Occurrences",
    category: "Edit",
    keybinding: "Ctrl+Shift+L",
    run: (ctx) => ctx.runEditorCommand("selectHighlights"),
  },
  {
    id: "editor.action.commentLine",
    title: "Toggle Line Comment",
    category: "Edit",
    keybinding: "Ctrl+/",
    run: (ctx) => ctx.runEditorCommand("comment"),
  },
  {
    id: "workbench.files.action.showActiveFileInExplorer",
    title: "Reveal Active File in Explorer",
    category: "File",
    run: (ctx) => ctx.revealActiveFile(),
  },
  {
    id: "editor.action.toggleWordWrap",
    title: "Toggle Word Wrap",
    category: "View",
    run: (ctx) => ctx.runEditorCommand("wordWrap"),
  },
  {
    id: "editor.action.toggleMinimap",
    title: "Toggle Minimap",
    category: "View",
    run: (ctx) => ctx.toggleMinimap(),
  },
  {
    id: "editor.action.toggleRelativeLineNumbers",
    title: "Toggle Relative Line Numbers",
    category: "View",
    run: (ctx) => ctx.runEditorCommand("relativeLines"),
  },
  {
    id: "editor.action.peekDefinition",
    title: "Peek Definition",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("peek"),
  },
  {
    id: "editor.action.rename",
    title: "Rename Symbol",
    category: "Edit",
    keybinding: "F2",
    run: (ctx) => ctx.runEditorCommand("rename"),
  },
  {
    id: "editor.action.findReferences",
    title: "Find All References",
    category: "Edit",
    keybinding: "Shift+F12",
    run: (ctx) => ctx.runEditorCommand("references"),
  },
  {
    id: "editor.action.revealDefinition",
    title: "Go to Definition",
    category: "Edit",
    keybinding: "F12",
    run: (ctx) => ctx.runEditorCommand("definition"),
  },
  {
    id: "workbench.action.gotoSymbol",
    title: "Go to Symbol in Editor",
    category: "Edit",
    keybinding: "Ctrl+Shift+O",
    run: (ctx) => ctx.openSymbols(),
  },
  {
    id: "workbench.action.showAllSymbols",
    title: "Go to Symbol in Workspace",
    category: "Go",
    keybinding: "Ctrl+T",
    run: (ctx) => ctx.openWorkspaceSymbols(),
  },
  {
    id: "editor.action.gotoLine",
    title: "Go to Line",
    category: "Edit",
    keybinding: "Ctrl+G",
    run: (ctx) => ctx.runEditorCommand("goto"),
  },
  {
    id: "editor.action.copyLinesDown",
    title: "Copy Line Down",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("copyLineDown"),
  },
  {
    id: "editor.action.moveLinesUp",
    title: "Move Line Up",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("moveLineUp"),
  },
  {
    id: "editor.action.moveLinesDown",
    title: "Move Line Down",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("moveLineDown"),
  },
  {
    id: "editor.action.startFindReplaceAction",
    title: "Replace in File",
    category: "Edit",
    keybinding: "Ctrl+H",
    run: (ctx) => ctx.runEditorCommand("replace"),
  },
  {
    id: "actions.find",
    title: "Find in File",
    category: "Edit",
    keybinding: "Ctrl+F",
    run: (ctx) => ctx.findInFile(),
  },
  {
    id: "workbench.action.findInFiles",
    title: "Search in Workspace",
    category: "Edit",
    keybinding: "Ctrl+Shift+F",
    run: (ctx) => ctx.openSearch(),
  },
  {
    id: "workbench.action.terminal.toggle",
    title: "Toggle Terminal",
    category: "View",
    keybinding: "Ctrl+`",
    run: (ctx) => ctx.toggleTerminal(),
  },
  {
    id: "workbench.action.terminal.clearAll",
    title: "Clear All Terminals",
    category: "Terminal",
    run: (ctx) => ctx.clearAllTerminals(),
  },
  {
    id: "workbench.action.runFile",
    title: "Run File",
    category: "Run",
    keybinding: "Ctrl+F5",
    run: (ctx) => ctx.runFile(),
  },
  {
    id: "workbench.actions.view.problems",
    title: "Show Problems",
    category: "View",
    keybinding: "Ctrl+Shift+M",
    run: (ctx) => ctx.openProblems(),
  },
  {
    id: "workbench.action.toggleAi",
    title: "Toggle AI Agent",
    category: "View",
    keybinding: "Ctrl+Shift+A",
    run: (ctx) => ctx.toggleAi(),
  },
  {
    id: "workbench.view.extensions",
    title: "Show Extensions",
    category: "View",
    run: (ctx) => ctx.openExtensions(),
  },
  {
    id: "workbench.view.debug",
    title: "Show Run and Debug",
    category: "View",
    run: (ctx) => ctx.openDebug(),
  },
  {
    id: "workbench.action.openSettings",
    title: "Open Settings",
    category: "Preferences",
    keybinding: "Ctrl+,",
    run: (ctx) => ctx.openSettings(),
  },
  {
    id: "workbench.action.toggleSidebarVisibility",
    title: "Toggle Primary Side Bar",
    category: "View",
    keybinding: "Ctrl+B",
    run: (ctx) => ctx.toggleSidebar(),
  },
];
