import type { Command } from "./types";

export const COMMANDS: Command[] = [
  {
    id: "workbench.action.showCommands",
    title: "Show All Commands",
    category: "View",
    keybinding: "Ctrl+Shift+P",
    run: (ctx) => ctx.openPalette(),
  },
  {
    id: "workbench.action.reopenClosedEditor",
    title: "Reopen Closed Editor",
    category: "View",
    keybinding: "Ctrl+Shift+T",
    run: (ctx) => void ctx.reopenClosed(),
  },
  {
    id: "git.clone",
    title: "Clone Repository…",
    category: "Git",
    run: (ctx) => void ctx.cloneRepository(),
  },
  {
    id: "workbench.action.files.openFolder",
    title: "Open Folder…",
    category: "File",
    keybinding: "Ctrl+K Ctrl+O",
    run: (ctx) => void ctx.openFolder(),
  },
  {
    id: "workbench.action.files.save",
    title: "Save",
    category: "File",
    keybinding: "Ctrl+S",
    run: (ctx) => void ctx.save(),
  },
  {
    id: "workbench.action.files.saveAs",
    title: "Save As…",
    category: "File",
    keybinding: "Ctrl+Shift+S",
    run: (ctx) => void ctx.saveAs(),
  },
  {
    id: "workbench.action.files.saveAll",
    title: "Save All",
    category: "File",
    keybinding: "Ctrl+K S",
    run: (ctx) => void ctx.saveAll(),
  },
  {
    id: "workbench.action.closeActiveEditor",
    title: "Close Editor",
    category: "View",
    keybinding: "Ctrl+W",
    run: (ctx) => ctx.closeActive(),
  },
  {
    id: "workbench.action.closeAllEditors",
    title: "Close All Editors",
    category: "View",
    keybinding: "Ctrl+K W",
    run: (ctx) => ctx.closeAll(),
  },
  {
    id: "workbench.action.toggleTheme",
    title: "Toggle Light/Dark Theme",
    category: "Preferences",
    keybinding: "Ctrl+K Ctrl+T",
    run: (ctx) => ctx.toggleTheme(),
  },
  {
    id: "editor.action.commentLine",
    title: "Toggle Line Comment",
    category: "Edit",
    keybinding: "Ctrl+/",
    run: (ctx) => ctx.runEditorCommand("comment"),
  },
  {
    id: "editor.action.toggleWordWrap",
    title: "Toggle Word Wrap",
    category: "View",
    run: (ctx) => ctx.runEditorCommand("wordWrap"),
  },
  {
    id: "editor.action.toggleMinimap",
    title: "Toggle Minimap",
    category: "View",
    run: (ctx) => ctx.toggleMinimap(),
  },
  {
    id: "editor.action.toggleRelativeLineNumbers",
    title: "Toggle Relative Line Numbers",
    category: "View",
    run: (ctx) => ctx.runEditorCommand("relativeLines"),
  },
  {
    id: "editor.action.peekDefinition",
    title: "Peek Definition",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("peek"),
  },
  {
    id: "editor.action.rename",
    title: "Rename Symbol",
    category: "Edit",
    keybinding: "F2",
    run: (ctx) => ctx.runEditorCommand("rename"),
  },
  {
    id: "editor.action.findReferences",
    title: "Find All References",
    category: "Edit",
    keybinding: "Shift+F12",
    run: (ctx) => ctx.runEditorCommand("references"),
  },
  {
    id: "editor.action.revealDefinition",
    title: "Go to Definition",
    category: "Edit",
    keybinding: "F12",
    run: (ctx) => ctx.runEditorCommand("definition"),
  },
  {
    id: "workbench.action.gotoSymbol",
    title: "Go to Symbol in Editor",
    category: "Edit",
    keybinding: "Ctrl+Shift+O",
    run: (ctx) => ctx.openSymbols(),
  },
  {
    id: "editor.action.gotoLine",
    title: "Go to Line",
    category: "Edit",
    keybinding: "Ctrl+G",
    run: (ctx) => ctx.runEditorCommand("goto"),
  },
  {
    id: "editor.action.copyLinesDown",
    title: "Copy Line Down",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("copyLineDown"),
  },
  {
    id: "editor.action.moveLinesUp",
    title: "Move Line Up",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("moveLineUp"),
  },
  {
    id: "editor.action.moveLinesDown",
    title: "Move Line Down",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("moveLineDown"),
  },
  {
    id: "editor.action.startFindReplaceAction",
    title: "Replace in File",
    category: "Edit",
    keybinding: "Ctrl+H",
    run: (ctx) => ctx.runEditorCommand("replace"),
  },
  {
    id: "actions.find",
    title: "Find in File",
    category: "Edit",
    keybinding: "Ctrl+F",
    run: (ctx) => ctx.findInFile(),
  },
  {
    id: "workbench.action.findInFiles",
    title: "Search in Workspace",
    category: "Edit",
    keybinding: "Ctrl+Shift+F",
    run: (ctx) => ctx.openSearch(),
  },
  {
    id: "workbench.action.terminal.toggle",
    title: "Toggle Terminal",
    category: "View",
    keybinding: "Ctrl+`",
    run: (ctx) => ctx.toggleTerminal(),
  },
  {
    id: "workbench.actions.view.problems",
    title: "Show Problems",
    category: "View",
    keybinding: "Ctrl+Shift+M",
    run: (ctx) => ctx.openProblems(),
  },
  {
    id: "workbench.action.toggleAi",
    title: "Toggle AI Agent",
    category: "View",
    keybinding: "Ctrl+Shift+A",
    run: (ctx) => ctx.toggleAi(),
  },
  {
    id: "workbench.view.extensions",
    title: "Show Extensions",
    category: "View",
    run: (ctx) => ctx.openExtensions(),
  },
  {
    id: "workbench.view.debug",
    title: "Show Run and Debug",
    category: "View",
    run: (ctx) => ctx.openDebug(),
  },
  {
    id: "workbench.action.openSettings",
    title: "Open Settings",
    category: "Preferences",
    keybinding: "Ctrl+,",
    run: (ctx) => ctx.openSettings(),
  },
  {
    id: "workbench.action.toggleSidebarVisibility",
    title: "Toggle Primary Side Bar",
    category: "View",
    keybinding: "Ctrl+B",
    run: (ctx) => ctx.toggleSidebar(),
  },
];
