import type { Command } from "./types";

export const COMMANDS: Command[] = [
  {
    id: "workbench.action.showCommands",
    title: "Show All Commands",
    category: "View",
    keybinding: "Ctrl+Shift+P",
    run: (ctx) => ctx.openPalette(),
  },
  {
    id: "workbench.action.reopenClosedEditor",
    title: "Reopen Closed Editor",
    category: "View",
    keybinding: "Ctrl+Shift+T",
    run: (ctx) => void ctx.reopenClosed(),
  },
  {
    id: "git.clone",
    title: "Clone Repository…",
    category: "Git",
    run: (ctx) => void ctx.cloneRepository(),
  },
  {
    id: "workbench.action.files.openFolder",
    title: "Open Folder…",
    category: "File",
    keybinding: "Ctrl+K Ctrl+O",
    run: (ctx) => void ctx.openFolder(),
  },
  {
    id: "workbench.action.closeFolder",
    title: "Close Folder",
    category: "File",
    run: (ctx) => ctx.closeFolder(),
  },
  {
    id: "workbench.files.action.refreshFilesExplorer",
    title: "Refresh Explorer",
    category: "File",
    run: (ctx) => void ctx.refreshExplorer(),
  },
  {
    id: "workbench.files.action.collapseExplorerFolders",
    title: "Collapse Folders in Explorer",
    category: "File",
    run: (ctx) => ctx.collapseExplorer(),
  },
  {
    id: "workbench.files.action.expandExplorerFolders",
    title: "Expand Folders in Explorer",
    category: "File",
    run: (ctx) => ctx.expandExplorer(),
  },
  {
    id: "workbench.action.quickOpen",
    title: "Go to File…",
    category: "Go",
    keybinding: "Ctrl+P",
    run: (ctx) => ctx.openGoToFile(),
  },
  {
    id: "workbench.action.openGlobalKeybindings",
    title: "Keyboard Shortcuts",
    category: "Preferences",
    keybinding: "Ctrl+K Ctrl+S",
    run: (ctx) => ctx.openKeybindings(),
  },
  {
    id: "workbench.action.addRootFolder",
    title: "Add Folder to Workspace…",
    category: "File",
    run: (ctx) => void ctx.addFolderRoot(),
  },
  {
    id: "workbench.action.addActiveFileFolderToWorkspace",
    title: "Add Active File Folder to Workspace",
    category: "File",
    run: (ctx) => void ctx.addActiveFolderRoot(),
  },
  {
    id: "workbench.action.removeRootFolder",
    title: "Remove Folder from Workspace…",
    category: "File",
    run: (ctx) => {
      const path = window.prompt("Folder path to remove from the workspace:");
      if (!path?.trim()) return;
      void ctx.removeFolderRoot(path.trim());
    },
  },
  {
    id: "workbench.action.reopenRemovedRootFolder",
    title: "Reopen Closed Folder Root",
    category: "File",
    run: (ctx) => void ctx.reopenRemovedRoot(),
  },
  {
    id: "workbench.action.files.save",
    title: "Save",
    category: "File",
    keybinding: "Ctrl+S",
    run: (ctx) => void ctx.save(),
  },
  {
    id: "workbench.action.files.saveAs",
    title: "Save As…",
    category: "File",
    keybinding: "Ctrl+Shift+S",
    run: (ctx) => void ctx.saveAs(),
  },
  {
    id: "workbench.action.files.saveAll",
    title: "Save All",
    category: "File",
    keybinding: "Ctrl+K S",
    run: (ctx) => void ctx.saveAll(),
  },
  {
    id: "workbench.action.closeActiveEditor",
    title: "Close Editor",
    category: "View",
    keybinding: "Ctrl+W",
    run: (ctx) => ctx.closeActive(),
  },
  {
    id: "workbench.action.closeAllEditors",
    title: "Close All Editors",
    category: "View",
    keybinding: "Ctrl+K W",
    run: (ctx) => ctx.closeAll(),
  },
  {
    id: "workbench.action.closeOtherEditors",
    title: "Close Other Editors",
    category: "View",
    run: (ctx) => ctx.closeOtherEditors(),
  },
  {
    id: "workbench.action.closeUnmodifiedEditors",
    title: "Close Saved Editors",
    category: "View",
    run: (ctx) => ctx.closeSavedEditors(),
  },
  {
    id: "workbench.action.pinEditor",
    title: "Pin Active Editor",
    category: "View",
    when: (ctx) => !ctx.activeEditorPinned,
    run: (ctx) => ctx.pinActiveEditor(),
  },
  {
    id: "workbench.action.unpinEditor",
    title: "Unpin Active Editor",
    category: "View",
    when: (ctx) => ctx.activeEditorPinned,
    run: (ctx) => ctx.unpinActiveEditor(),
  },
  {
    id: "copyFilePath",
    title: "Copy Path of Active File",
    category: "File",
    run: (ctx) => ctx.copyActivePath(),
  },
  {
    id: "copyRelativeFilePath",
    title: "Copy Relative Path of Active File",
    category: "File",
    run: (ctx) => ctx.copyActiveRelativePath(),
  },
  {
    id: "workbench.action.toggleTheme",
    title: "Toggle Light/Dark Theme",
    category: "Preferences",
    keybinding: "Ctrl+K Ctrl+T",
    run: (ctx) => ctx.toggleTheme(),
  },
  {
    id: "editor.action.toggleStickyScroll",
    title: "Toggle Sticky Scroll",
    category: "View",
    run: (ctx) => ctx.toggleStickyScroll(),
  },
  {
    id: "editor.action.formatDocument",
    title: "Format Document",
    category: "Edit",
    keybinding: "Shift+Alt+F",
    run: (ctx) => ctx.runEditorCommand("format"),
  },
  {
    id: "editor.action.showHover",
    title: "Show Hover",
    category: "Edit",
    keybinding: "Ctrl+K Ctrl+I",
    run: (ctx) => ctx.runEditorCommand("hover"),
  },
  {
    id: "editor.action.addSelectionToNextFindMatch",
    title: "Add Selection To Next Find Match",
    category: "Edit",
    keybinding: "Ctrl+D",
    run: (ctx) => ctx.runEditorCommand("addNextMatch"),
  },
  {
    id: "editor.foldAll",
    title: "Fold All",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("foldAll"),
  },
  {
    id: "editor.unfoldAll",
    title: "Unfold All",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("unfoldAll"),
  },
  {
    id: "editor.action.transformToUppercase",
    title: "Transform to Uppercase",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("uppercase"),
  },
  {
    id: "editor.action.transformToLowercase",
    title: "Transform to Lowercase",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("lowercase"),
  },
  {
    id: "editor.action.transformToTitlecase",
    title: "Transform to Title Case",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("titlecase"),
  },
  {
    id: "editor.action.blockComment",
    title: "Toggle Block Comment",
    category: "Edit",
    keybinding: "Shift+Alt+A",
    run: (ctx) => ctx.runEditorCommand("blockComment"),
  },
  {
    id: "editor.action.joinLines",
    title: "Join Lines",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("joinLines"),
  },
  {
    id: "editor.action.sortLinesAscending",
    title: "Sort Lines Ascending",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("sortLines"),
  },
  {
    id: "editor.action.duplicateSelection",
    title: "Duplicate Selection",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("duplicateSelection"),
  },
  {
    id: "editor.action.transposeLetters",
    title: "Transpose Letters",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("transposeLetters"),
  },
  {
    id: "editor.action.jumpToBracket",
    title: "Go to Matching Bracket",
    category: "Go",
    run: (ctx) => ctx.runEditorCommand("jumpToBracket"),
  },
  {
    id: "editor.action.selectHighlights",
    title: "Select All Occurrences",
    category: "Edit",
    keybinding: "Ctrl+Shift+L",
    run: (ctx) => ctx.runEditorCommand("selectHighlights"),
  },
  {
    id: "editor.action.smartSelect.expand",
    title: "Expand Selection",
    category: "Edit",
    keybinding: "Shift+Alt+Right",
    run: (ctx) => ctx.runEditorCommand("smartSelectExpand"),
  },
  {
    id: "editor.action.smartSelect.shrink",
    title: "Shrink Selection",
    category: "Edit",
    keybinding: "Shift+Alt+Left",
    run: (ctx) => ctx.runEditorCommand("smartSelectShrink"),
  },
  {
    id: "editor.action.commentLine",
    title: "Toggle Line Comment",
    category: "Edit",
    keybinding: "Ctrl+/",
    run: (ctx) => ctx.runEditorCommand("comment"),
  },
  {
    id: "workbench.files.action.showActiveFileInExplorer",
    title: "Reveal Active File in Explorer",
    category: "File",
    run: (ctx) => ctx.revealActiveFile(),
  },
  {
    id: "editor.action.toggleWordWrap",
    title: "Toggle Word Wrap",
    category: "View",
    run: (ctx) => ctx.toggleWordWrap(),
  },
  {
    id: "editor.action.toggleRenderWhitespace",
    title: "Toggle Render Whitespace",
    category: "View",
    run: (ctx) => ctx.toggleRenderWhitespace(),
  },
  {
    id: "editor.action.toggleRelativeLineNumbers",
    title: "Toggle Relative Line Numbers",
    category: "View",
    run: (ctx) => ctx.toggleRelativeLineNumbers(),
  },
  {
    id: "editor.action.toggleInsertFinalNewline",
    title: "Toggle Insert Final Newline",
    category: "View",
    run: (ctx) => ctx.toggleInsertFinalNewline(),
  },
  {
    id: "editor.action.toggleTrimTrailingWhitespace",
    title: "Toggle Trim Trailing Whitespace",
    category: "View",
    run: (ctx) => ctx.toggleTrimTrailingWhitespace(),
  },
  {
    id: "editor.action.cycleAutoSave",
    title: "Cycle Auto Save",
    category: "Preferences",
    run: (ctx) => ctx.cycleAutoSave(),
  },
  {
    id: "editor.action.cycleFontSize",
    title: "Cycle Editor Font Size",
    category: "Preferences",
    run: (ctx) => ctx.cycleFontSize(),
  },
  {
    id: "editor.action.cycleCursorStyle",
    title: "Cycle Cursor Style",
    category: "Preferences",
    run: (ctx) => ctx.cycleCursorStyle(),
  },
  {
    id: "editor.action.cycleTabSize",
    title: "Cycle Tab Size",
    category: "Preferences",
    run: (ctx) => ctx.cycleTabSize(),
  },
  {
    id: "editor.action.cycleTerminalFontSize",
    title: "Cycle Terminal Font Size",
    category: "Preferences",
    run: (ctx) => ctx.cycleTerminalFontSize(),
  },
  {
    id: "editor.action.toggleLineNumbers",
    title: "Toggle Line Numbers",
    category: "View",
    run: (ctx) => ctx.toggleLineNumbers(),
  },
  {
    id: "editor.action.toggleMinimap",
    title: "Toggle Minimap",
    category: "View",
    run: (ctx) => ctx.toggleMinimap(),
  },
  {
    id: "editor.action.toggleRelativeLineNumbers",
    title: "Toggle Relative Line Numbers",
    category: "View",
    run: (ctx) => ctx.runEditorCommand("relativeLines"),
  },
  {
    id: "editor.action.peekDefinition",
    title: "Peek Definition",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("peek"),
  },
  {
    id: "editor.action.rename",
    title: "Rename Symbol",
    category: "Edit",
    keybinding: "F2",
    run: (ctx) => ctx.runEditorCommand("rename"),
  },
  {
    id: "editor.action.findReferences",
    title: "Find All References",
    category: "Edit",
    keybinding: "Shift+F12",
    run: (ctx) => ctx.runEditorCommand("references"),
  },
  {
    id: "editor.action.revealDefinition",
    title: "Go to Definition",
    category: "Edit",
    keybinding: "F12",
    run: (ctx) => ctx.runEditorCommand("definition"),
  },
  {
    id: "workbench.action.gotoSymbol",
    title: "Go to Symbol in Editor",
    category: "Edit",
    keybinding: "Ctrl+Shift+O",
    run: (ctx) => ctx.openSymbols(),
  },
  {
    id: "workbench.action.showAllSymbols",
    title: "Go to Symbol in Workspace",
    category: "Go",
    keybinding: "Ctrl+T",
    run: (ctx) => ctx.openWorkspaceSymbols(),
  },
  {
    id: "editor.action.gotoLine",
    title: "Go to Line",
    category: "Edit",
    keybinding: "Ctrl+G",
    run: (ctx) => ctx.runEditorCommand("goto"),
  },
  {
    id: "editor.action.copyLinesDown",
    title: "Copy Line Down",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("copyLineDown"),
  },
  {
    id: "editor.action.copyLinesUp",
    title: "Copy Line Up",
    category: "Edit",
    keybinding: "Alt+Shift+Up",
    run: (ctx) => ctx.runEditorCommand("copyLineUp"),
  },
  {
    id: "editor.action.moveLinesUp",
    title: "Move Line Up",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("moveLineUp"),
  },
  {
    id: "editor.action.moveLinesDown",
    title: "Move Line Down",
    category: "Edit",
    run: (ctx) => ctx.runEditorCommand("moveLineDown"),
  },
  {
    id: "editor.action.startFindReplaceAction",
    title: "Replace in File",
    category: "Edit",
    keybinding: "Ctrl+H",
    run: (ctx) => ctx.runEditorCommand("replace"),
  },
  {
    id: "workbench.action.splitEditorRight",
    title: "Split Editor Right",
    category: "View",
    run: (ctx) => ctx.splitEditorRight(),
  },
  {
    id: "workbench.action.joinEditorGroup",
    title: "Close Editor Split",
    category: "View",
    run: (ctx) => ctx.closeEditorGroup(),
  },
  {
    id: "actions.find",
    title: "Find in File",
    category: "Edit",
    keybinding: "Ctrl+F",
    run: (ctx) => ctx.findInFile(),
  },
  {
    id: "actions.findWithSelection",
    title: "Find in Selection",
    category: "Edit",
    run: (ctx) => ctx.findInSelection(),
  },
  {
    id: "editor.action.startFindReplaceAction.inSelection",
    title: "Replace in Selection",
    category: "Edit",
    run: (ctx) => ctx.replaceInSelection(),
  },
  {
    id: "workbench.action.findInFiles",
    title: "Search in Workspace",
    category: "Edit",
    keybinding: "Ctrl+Shift+F",
    run: (ctx) => ctx.openSearch(),
  },
  {
    id: "workbench.action.terminal.toggle",
    title: "Toggle Terminal",
    category: "View",
    keybinding: "Ctrl+`",
    run: (ctx) => ctx.toggleTerminal(),
  },
  {
    id: "workbench.action.togglePanel",
    title: "Toggle Bottom Panel",
    category: "View",
    run: (ctx) => ctx.toggleBottomPanel(),
  },
  {
    id: "workbench.action.terminal.clear",
    title: "Clear Terminal",
    category: "Terminal",
    run: (ctx) => ctx.clearActiveTerminal(),
  },
  {
    id: "workbench.action.terminal.clearAll",
    title: "Clear All Terminals",
    category: "Terminal",
    run: (ctx) => ctx.clearAllTerminals(),
  },
  {
    id: "workbench.action.terminal.new",
    title: "New Terminal",
    category: "Terminal",
    keybinding: "Ctrl+Shift+`",
    run: (ctx) => ctx.newTerminal(),
  },
  {
    id: "workbench.action.terminal.kill",
    title: "Kill Active Terminal",
    category: "Terminal",
    run: (ctx) => ctx.killActiveTerminal(),
  },
  {
    id: "workbench.action.terminal.duplicate",
    title: "Duplicate Terminal",
    category: "Terminal",
    run: (ctx) => ctx.duplicateTerminal(),
  },
  {
    id: "workbench.action.terminal.focusNext",
    title: "Focus Next Terminal",
    category: "Terminal",
    run: (ctx) => ctx.focusNextTerminal(),
  },
  {
    id: "workbench.action.terminal.focusPrevious",
    title: "Focus Previous Terminal",
    category: "Terminal",
    run: (ctx) => ctx.focusPreviousTerminal(),
  },
  {
    id: "workbench.action.terminal.rename",
    title: "Rename Active Terminal",
    category: "Terminal",
    run: (ctx) => ctx.renameActiveTerminal(),
  },
  {
    id: "workbench.action.terminal.restart",
    title: "Restart Active Terminal",
    category: "Terminal",
    run: (ctx) => ctx.restartActiveTerminal(),
  },
  {
    id: "workbench.action.runFile",
    title: "Run File",
    category: "Run",
    keybinding: "Ctrl+F5",
    run: (ctx) => ctx.runFile(),
  },
  {
    id: "workbench.actions.view.problems",
    title: "Show Problems",
    category: "View",
    keybinding: "Ctrl+Shift+M",
    run: (ctx) => ctx.openProblems(),
  },
  {
    id: "workbench.action.output.toggleOutput",
    title: "Show Logs",
    category: "View",
    run: (ctx) => ctx.openLogs(),
  },
  {
    id: "workbench.actions.view.toggleProblems",
    title: "Toggle Problems",
    category: "View",
    run: (ctx) => ctx.toggleProblems(),
  },
  {
    id: "git.viewAmend",
    title: "Toggle Amend Last Commit",
    category: "Git",
    run: (ctx) => ctx.toggleScmAmend(),
  },
  {
    id: "workbench.action.toggleAi",
    title: "Toggle AI Agent",
    category: "View",
    keybinding: "Ctrl+Shift+A",
    run: (ctx) => ctx.toggleAi(),
  },
  {
    id: "workbench.view.extensions",
    title: "Show Extensions",
    category: "View",
    run: (ctx) => ctx.openExtensions(),
  },
  {
    id: "workbench.view.debug",
    title: "Show Run and Debug",
    category: "View",
    run: (ctx) => ctx.openDebug(),
  },
  {
    id: "workbench.action.openSettings",
    title: "Open Settings",
    category: "Preferences",
    keybinding: "Ctrl+,",
    run: (ctx) => ctx.openSettings(),
  },
  {
    id: "workbench.action.toggleSidebarVisibility",
    title: "Toggle Primary Side Bar",
    category: "View",
    keybinding: "Ctrl+B",
    run: (ctx) => ctx.toggleSidebar(),
  },
  {
    id: "workbench.action.clearAiAttachments",
    title: "Clear AI Attachments",
    category: "AI",
    run: (ctx) => ctx.clearAiAttachments(),
  },
  {
    id: "workbench.action.clearAiChat",
    title: "Clear AI Chat",
    category: "AI",
    run: (ctx) => ctx.clearAiChat(),
  },
  {
    id: "workbench.action.exportAiSession",
    title: "Export AI Session",
    category: "AI",
    run: (ctx) => ctx.exportAiSession(),
  },
  {
    id: "workbench.action.importAiSession",
    title: "Import AI Session",
    category: "AI",
    run: (ctx) => ctx.importAiSession(),
  },
  {
    id: "workbench.action.newAiChat",
    title: "New AI Chat",
    category: "AI",
    run: (ctx) => ctx.newAiChat(),
  },
  {
    id: "workbench.view.explorer",
    title: "Show Explorer",
    category: "View",
    run: (ctx) => ctx.showExplorer(),
  },
  {
    id: "workbench.view.search",
    title: "Show Search",
    category: "View",
    run: (ctx) => ctx.showSearch(),
  },
  {
    id: "workbench.view.scm",
    title: "Show Source Control",
    category: "View",
    run: (ctx) => ctx.showScm(),
  },
  {
    id: "workbench.view.outline",
    title: "Show Outline",
    category: "View",
    run: (ctx) => ctx.showOutline(),
  },
  {
    id: "workbench.action.reopenLastFolder",
    title: "Reopen Last Folder",
    category: "File",
    run: (ctx) => ctx.reopenLastFolder(),
  },
  {
    id: "workbench.action.showWelcomePage",
    title: "Show Welcome",
    category: "Help",
    run: (ctx) => ctx.showWelcome(),
  },
  {
    id: "workbench.action.openAi",
    title: "Show AI Agent",
    category: "View",
    run: (ctx) => ctx.openAi(),
  },
  {
    id: "git.pull",
    title: "Git: Pull",
    category: "Git",
    run: (ctx) => ctx.gitPull(),
  },
  {
    id: "git.push",
    title: "Git: Push",
    category: "Git",
    run: (ctx) => ctx.gitPush(),
  },
  {
    id: "git.fetch",
    title: "Git: Fetch",
    category: "Git",
    run: (ctx) => ctx.gitFetch(),
  },
  {
    id: "git.stash",
    title: "Git: Stash",
    category: "Git",
    run: (ctx) => ctx.gitStash(),
  },
  {
    id: "git.stashPop",
    title: "Git: Pop Stash",
    category: "Git",
    run: (ctx) => ctx.gitStashPop(),
  },
  {
    id: "workbench.action.files.newUntitledFile",
    title: "New Untitled File",
    category: "File",
    keybinding: "Ctrl+N",
    run: (ctx) => ctx.openUntitled(),
  },
  {
    id: "workbench.actions.view.cycleProblemsFilter",
    title: "Cycle Problems Severity Filter",
    category: "View",
    run: (ctx) => ctx.cycleProblemsFilter(),
  },
  {
    id: "workbench.action.terminal.focus",
    title: "Focus Active Terminal",
    category: "Terminal",
    run: (ctx) => ctx.focusActiveTerminal(),
  },
  {
    id: "workbench.action.duplicateEditorToSide",
    title: "Duplicate Editor to the Side",
    category: "View",
    run: (ctx) => ctx.duplicateEditorToSide(),
  },
  {
    id: "git.createBranch",
    title: "Git: Create Branch",
    category: "Git",
    run: (ctx) => ctx.gitCreateBranch(),
  },
  {
    id: "git.checkout",
    title: "Git: Checkout Branch",
    category: "Git",
    run: (ctx) => ctx.gitCheckout(),
  },
  {
    id: "editor.action.cycleRulers",
    title: "Cycle Editor Rulers",
    category: "Preferences",
    run: (ctx) => ctx.cycleRulers(),
  },
  {
    id: "editor.action.cycleWordWrapColumn",
    title: "Cycle Word Wrap Column",
    category: "Preferences",
    run: (ctx) => ctx.cycleWordWrapColumn(),
  },
  {
    id: "workbench.action.clearLogs",
    title: "Clear Logs",
    category: "View",
    run: (ctx) => ctx.clearLogs(),
  },
  {
    id: "revealFileInOS",
    title: "Reveal Active File in File Manager",
    category: "File",
    run: (ctx) => ctx.revealActiveFileInOs(),
  },
  {
    id: "git.discardAllUnstaged",
    title: "Git: Discard All Unstaged Changes",
    category: "Git",
    run: (ctx) => ctx.gitDiscardAll(),
  },
  {
    id: "git.stageAll",
    title: "Git: Stage All Changes",
    category: "Git",
    run: (ctx) => ctx.gitStageAll(),
  },
  {
    id: "git.unstageAll",
    title: "Git: Unstage All Changes",
    category: "Git",
    run: (ctx) => ctx.gitUnstageAll(),
  },
  {
    id: "workbench.action.cycleAiMaxToolRounds",
    title: "Cycle AI Max Tool Rounds",
    category: "AI",
    run: (ctx) => ctx.cycleAiMaxToolRounds(),
  },
  {
    id: "workbench.files.action.revealParentInExplorer",
    title: "Reveal Parent Folder in Explorer",
    category: "File",
    run: (ctx) => ctx.revealActiveParentInExplorer(),
  },
  {
    id: "git.copyRelativePath",
    title: "Git: Copy Relative Path of Selected",
    category: "Git",
    run: (ctx) => ctx.gitCopyRelativePaths(),
  },
  {
    id: "git.copyPath",
    title: "Git: Copy Absolute Path of Selected",
    category: "Git",
    run: (ctx) => ctx.gitCopyAbsolutePaths(),
  },
  {
    id: "git.openSelected",
    title: "Git: Open Selected",
    category: "Git",
    run: (ctx) => ctx.gitOpenSelected(),
  },
  {
    id: "workbench.action.cycleAiRequestTimeout",
    title: "Cycle AI Request Timeout",
    category: "AI",
    run: (ctx) => ctx.cycleAiRequestTimeout(),
  },
  {
    id: "workbench.action.toggleAiStopOnToolError",
    title: "Toggle AI Stop on Tool Error",
    category: "AI",
    run: (ctx) => ctx.toggleAiStopOnToolError(),
  },
  {
    id: "git.selectAll",
    title: "Git: Select All Changes",
    category: "Git",
    run: (ctx) => ctx.gitSelectAll(),
  },
  {
    id: "git.deselectAll",
    title: "Git: Deselect All Changes",
    category: "Git",
    run: (ctx) => ctx.gitDeselectAll(),
  },
  {
    id: "git.stageSelected",
    title: "Git: Stage Selected",
    category: "Git",
    run: (ctx) => ctx.gitStageSelected(),
  },
  {
    id: "git.unstageSelected",
    title: "Git: Unstage Selected",
    category: "Git",
    run: (ctx) => ctx.gitUnstageSelected(),
  },
  {
    id: "git.discardSelected",
    title: "Git: Discard Selected",
    category: "Git",
    run: (ctx) => ctx.gitDiscardSelected(),
  },
  {
    id: "git.copyBranch",
    title: "Git: Copy Current Branch Name",
    category: "Git",
    run: (ctx) => ctx.gitCopyBranch(),
  },
  {
    id: "workbench.action.cycleAiTemperature",
    title: "Cycle AI Temperature",
    category: "AI",
    run: (ctx) => ctx.cycleAiTemperature(),
  },
  {
    id: "workbench.action.toggleAiShowHistory",
    title: "Toggle AI Session History",
    category: "AI",
    run: (ctx) => ctx.toggleAiShowHistory(),
  },
  {
    id: "git.ignoreSelected",
    title: "Git: Ignore Selected",
    category: "Git",
    run: (ctx) => ctx.gitIgnoreSelected(),
  },
  {
    id: "git.compareSelected",
    title: "Git: Compare Selected with HEAD",
    category: "Git",
    run: (ctx) => ctx.gitCompareSelected(),
  },
  {
    id: "workbench.action.cycleAiTopP",
    title: "Cycle AI Top P",
    category: "AI",
    run: (ctx) => ctx.cycleAiTopP(),
  },
  {
    id: "workbench.action.cycleAiMaxTokens",
    title: "Cycle AI Max Tokens",
    category: "AI",
    run: (ctx) => ctx.cycleAiMaxTokens(),
  },
  {
    id: "workbench.action.cycleAiPresencePenalty",
    title: "Cycle AI Presence Penalty",
    category: "AI",
    run: (ctx) => ctx.cycleAiPresencePenalty(),
  },
  {
    id: "workbench.view.scm",
    title: "Focus on Source Control View",
    category: "View",
    run: (ctx) => ctx.focusScm(),
  },
  {
    id: "workbench.action.cycleAiFrequencyPenalty",
    title: "Cycle AI Frequency Penalty",
    category: "AI",
    run: (ctx) => ctx.cycleAiFrequencyPenalty(),
  },
  {
    id: "workbench.action.focusAiSystemPrompt",
    title: "Focus AI System Prompt",
    category: "AI",
    run: (ctx) => ctx.focusAiSystemPrompt(),
  },
  {
    id: "git.revealSelected",
    title: "Git: Reveal Selected in File Manager",
    category: "Git",
    run: (ctx) => ctx.gitRevealSelected(),
  },
  {
    id: "git.refresh",
    title: "Git: Refresh",
    category: "Git",
    run: (ctx) => ctx.gitRefresh(),
  },
  {
    id: "diff.toggleIgnoreWhitespace",
    title: "Toggle Diff Ignore Whitespace",
    category: "Diff",
    run: (ctx) => ctx.toggleDiffIgnoreWhitespace(),
  },
  {
    id: "workbench.view.explorer",
    title: "Focus on Explorer View",
    category: "View",
    run: (ctx) => ctx.focusExplorer(),
  },
  {
    id: "workbench.action.focusSearch",
    title: "Focus on Search View",
    category: "View",
    run: (ctx) => ctx.focusSearch(),
  },
  {
    id: "workbench.action.focusExtensions",
    title: "Focus on Extensions View",
    category: "View",
    run: (ctx) => ctx.focusExtensions(),
  },
  {
    id: "workbench.action.focusDebug",
    title: "Focus on Run and Debug View",
    category: "View",
    run: (ctx) => ctx.focusDebug(),
  },
  {
    id: "workbench.action.focusOutline",
    title: "Focus on Outline View",
    category: "View",
    run: (ctx) => ctx.focusOutline(),
  },
  {
    id: "editor.action.cycleFontFamily",
    title: "Cycle Editor Font Family",
    category: "Preferences",
    run: (ctx) => ctx.cycleFontFamily(),
  },
  {
    id: "git.focusCommitMessage",
    title: "Git: Focus Commit Message",
    category: "Git",
    run: (ctx) => ctx.gitFocusCommitMessage(),
  },
];
